spring:
  application:
    name: PAYMENT-SERVICE
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: test
#    url: ${DB_URL}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  config:
    import: "optional:configserver:http://localhost:9296"

server:
  port: 8081

